import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'question.freezed.dart';
// optional: Since our Question class is serializable, we must add this line.
// But if Question was not serializable, we could skip it.
part 'question.g.dart';

@freezed
abstract class Question with _$Question {
  const factory Question({
    required String content,
    required List<String> hints,
  }) = _Person;

  factory Question.fromJson(Map<String, Object?> json) =>
      _$PersonFromJson(json);
}
